# Generated by Django 5.1.7 on 2025-03-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recapmodel',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
